import { expect, test } from '@playwright/test'

test('renders dashboard charts and their empty states', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Rozkład kolekcji' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Stan posiadania' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Status ukończenia' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Stan', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Według platformy' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Zakupy w czasie' })).toBeVisible()
  await expect(page.getByText('Dodaj pierwszy egzemplarz, aby zobaczyć rozkład platform.')).toBeVisible()
  await expect(page.getByText('Dodaj egzemplarz lub plan, aby zobaczyć stan posiadania.')).toBeVisible()
  await expect(page.getByText('Dodaj pierwszy egzemplarz, aby zobaczyć status ukończenia.')).toBeVisible()
  await expect(page.getByText('Dodaj używany lub zafoliowany egzemplarz, aby zobaczyć stan.')).toBeVisible()
  await expect(page.getByText('Brak cen zakupów do pokazania.')).toBeVisible()
  await expect(page.getByText('Dodaj daty zakupu, aby zobaczyć oś czasu.')).toBeVisible()
})

test('switches language and keeps the preference after navigation', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('link', { name: 'Ustawienia' }).click()
  await page.getByLabel('Język aplikacji', { exact: true }).selectOption('en')
  await expect(page.locator('html')).toHaveAttribute('lang', 'en')
  await expect(page.getByRole('heading', { name: 'Settings' })).toBeVisible()
  await page.getByRole('link', { name: 'Overview' }).click()
  await expect(page.getByRole('heading', { name: /Your collection/ })).toBeVisible()
  await page.goto('/')
  await expect(page.getByRole('heading', { name: /Your collection/ })).toBeVisible()
})

test('adds and displays a canonical game', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: /Twoja kolekcja/ })).toBeVisible()
  await page.getByRole('link', { name: 'Kolekcja' }).click()
  await expect(page.locator('.filter-tabs').getByRole('button', { name: 'Ukończone', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Dodaj grę' }).first().click()
  await page.getByLabel('Tytuł gry').fill('Testowy tytuł')
  await page.getByRole('button', { name: 'Dodaj grę' }).last().click()
  await expect(page.getByText('Testowy tytuł')).toBeVisible()
  await page.locator('.group-toggle').filter({ hasText: 'Testowy tytuł' }).click()
  await page.getByRole('button', { name: 'Dodaj egzemplarz' }).first().click()
  await page.getByRole('textbox', { name: 'Platforma' }).fill('PS4')
  await page.getByRole('button', { name: 'Dodaj egzemplarz' }).last().click()

  const completionFilter = page.locator('.toolbar select').nth(1)
  await completionFilter.selectOption('not-started')
  await expect(page.getByText('Testowy tytuł')).toBeVisible()
  await completionFilter.selectOption('started')
  await expect(page.getByText('Testowy tytuł')).not.toBeVisible()
  await completionFilter.selectOption('finished')
  await expect(page.getByText('Testowy tytuł')).not.toBeVisible()
  await completionFilter.selectOption('all')
  await page.getByRole('button', { name: 'Edytuj egzemplarz' }).click()
  await page.getByRole('dialog').locator('select').nth(1).selectOption('not-completed')
  await page.getByRole('button', { name: 'Zapisz zmiany' }).click()
  await completionFilter.selectOption('started')
  await expect(page.getByText('Testowy tytuł')).toBeVisible()
  await completionFilter.selectOption('finished')
  await expect(page.getByText('Testowy tytuł')).not.toBeVisible()
  await completionFilter.selectOption('all')
  await page.getByRole('button', { name: 'Edytuj egzemplarz' }).click()
  await page.getByRole('dialog').locator('select').nth(1).selectOption('completed')
  await page.getByRole('button', { name: 'Zapisz zmiany' }).click()
  await completionFilter.selectOption('finished')
  await expect(page.getByText('Testowy tytuł')).toBeVisible()
  await completionFilter.selectOption('started')
  await expect(page.getByText('Testowy tytuł')).not.toBeVisible()
  await completionFilter.selectOption('all')

  const doesItPlayLink = page.getByRole('link', { name: 'Sprawdź Testowy tytuł w DoesItPlay' })
  await expect(doesItPlayLink).toHaveAttribute('href', 'https://www.doesitplay.org/list?platform=PS4')
  await expect(doesItPlayLink).toHaveAttribute('target', '_blank')
  await expect(doesItPlayLink).toHaveAttribute('rel', 'noreferrer')

  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('./games')
  const gameCard = page.locator('.canonical-card').filter({ hasText: 'Testowy tytuł' })
  await expect(gameCard).toBeVisible()
  const cardBox = await gameCard.boundingBox()
  const actionsBox = await gameCard.locator('.canonical-actions').boundingBox()
  expect(cardBox).not.toBeNull()
  expect(actionsBox).not.toBeNull()
  if (cardBox && actionsBox) {
    expect(cardBox.x + cardBox.width).toBeLessThanOrEqual(390)
    expect(actionsBox.x + actionsBox.width).toBeLessThanOrEqual(390)
  }
})
